# The workflow checks out the repository, installs pre-commit, and runs the autoupdate command.
# If there are any updates, it creates a pull request with the changes.

name: Pre-commit Update

on:
  schedule:
    - cron: '0 2 * * 1' # Mondays at 2 AM UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  auto-update:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: '3.13'
          gh-token: ${{ secrets.GH_TOKEN }}

      - name: Autoupdate pre-commit hooks
        run: uv run pre-commit autoupdate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: chore/pre-commit-autoupdate
          title: Update pre-commit hooks
          commit-message: 'chore(config): update pre-commit hooks'
          body: |
            This PR was created automatically by the pre-commit autoupdate workflow.
            It updates the pre-commit hooks to their latest versions.
          labels: update-hooks
