name: Semgrep

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * 0" # 00:00 every Sunday

jobs:
  semgrep_scan:
    name: Semgrep Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Run Semgrep
        run: |
          semgrep \
            --config auto \
            --error \
            --metrics=off
